### ISSUE TITLE
PydanticのベースモデルのテストがGithubActionsで落ちる

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/BirdXplorer#112]
# 改善詳細 / Details of Improvement
ローカルでテスト実行すると通るが、GitHub Actionsだとおちる。
ライブラリバージョンの問題か？

https://github.com/codeforjapan/BirdXplorer/actions/runs/11136341798/job/30947949969

**Comment by yu23ki14** [comment]
個別のテストは通っている

**Comment by sushichan044** [comment]
`pyproject.toml`でmypyのバージョン範囲を指定していないので、 tox と GitHub Actionsでバージョンがズレていそうですね
両者間でデフォルトで有効化されるルールが違っていてそこを踏んでいそうな予感です

**Comment by osoken** [comment]
pydantic のシグネチャ変更によるエラーでしたので、#115 で修正しておきました。
@yu23ki14  お手漉きのときにマージお願いします。
