### ISSUE TITLE
fix error on test

### ISSUE THREAD

**Issue by osoken** [codeforjapan/BirdXplorer#42]
# 改善詳細 / Details of Improvement

`tox` コマンドを走らせるとエラー

```
ERROR tests/routers/test_data.py::test_user_enrollments_get - DeprecationWarning: The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.
ERROR tests/routers/test_system.py::test_ping - DeprecationWarning: The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.
```

**Comment by osoken** [comment]
https://github.com/encode/starlette/pull/2526

**Comment by Nikhil14091997** [comment]
I am still facing this issue. Any suggestions, how can I fix it?
I tried adding the 
`@pytest.mark.filterwarnings("ignore:.*The 'app' shortcut is now deprecated.*:DeprecationWarning")`
in my code:

`from fastapi.testclient import TestClient
from main import app
import pytest

client = TestClient(app)

import warnings
warnings.simplefilter("always")

@pytest.mark.filterwarnings("ignore:.*The 'app' shortcut is now deprecated.*:DeprecationWarning")
def test_read_main():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "Welcome to FinanceBro!"}

`

Console output looks something like:
`platform win32 -- Python 3.10.7, pytest-8.0.2, pluggy-1.4.0
rootdir: C:\Users\nkumar82\OneDrive - Arizona State University\Documents\FinanceManagementApp\FinanceBro
plugins: anyio-4.3.0
collected 1 item

tests\test_main.py .                                                                                                      [100%] 

======================================================= warnings summary ======================================================= 
..\env\lib\site-packages\httpx\_client.py:680
  env\lib\site-packages\httpx\_client.py:680: DeprecationWarning: The 'app' shortcut is now deprecated. Use the explicit style 'transport=WSGITransport(app=...)' instead.
    warnings.warn(message, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================= 1 passed, 1 warning in 1.51s ================================================= `
