### ISSUE TITLE
真偽値（0 or 1）の型クラスをつくり、該当型のプロパティをNoteクラスに追加

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/BirdXplorer#6]
# 改善詳細 / Details of Improvement
## 型
tsvに入っている0,1の真偽値に対応する型を作成（binaryBool）

## 追加プロパティのリスト
- misleadingOther
- misleadingFactualError
- misleadingManipulatedMedia
- misleadingOutdatedInformation
- misleadingMissingImportantContext
- misleadingUnverifiedClaimAsFact
- misleadingSatire
- notMisleadingOther
- notMisleadingFactuallyCorrect
- notMisleadingOutdatedButNotWhenWritten
- notMisleadingClearlySatire
- notMisleadingPersonalOpinion
- trustworthySources
- isMediaNote

# スクリーンショット / Screenshot
- 画面のスクリーンショットやデザインのスクリーンショットなど

# 期待する見せ方・挙動 / Expected behavior
- ユーザーの操作フローやシステムのフローなど

# 動作環境・ブラウザ / Environment
- 対象としている環境、バグが生じるブラウザや関係するSaaSなど

**Comment by yu23ki14** [comment]
#11

**Comment by osoken** [comment]
closed via #30
