### ISSUE TITLE
API の prod の Dockerfile のサーブコマンドを `gunicorn` 使いたい

### ISSUE THREAD

**Issue by osoken** [codeforjapan/BirdXplorer#67]
# 改善詳細 / Details of Improvement
- 現行の Dockerfile だと環境によらず `uvicorn` で動かしているが、 `prod` なら `gunicorn` にしたい

**Comment by sushi-chaaaan** [comment]
これはおそらくDockerfileのARGだけでは分岐が難しいので、
Dockefileそのものを分ける方向で行くのが丸そうな気がします

- dev: `compose.yml`で`birdxplorer_api/Dockerfile.dev`を指定
- prod: docker runで`birdxplorer_api/Dockerfile`を指定

**Comment by sushi-chaaaan** [comment]
こうなると、api側はDockerfileを分けてmigrate側はARGで分岐することになるのか、
migrateをapiの作法に合わせたほうが良さそうですかね
