### ISSUE TITLE
millisecondsの型を汎用クラスにする

### ISSUE THREAD

**Issue by yu23ki14** [codeforjapan/BirdXplorer#8]
# 改善詳細 / Details of Improvement
- Noteクラス内のcreated_at_millisの定義を他のプロパティでも使えるように汎用化

# スクリーンショット / Screenshot
- 画面のスクリーンショットやデザインのスクリーンショットなど

# 期待する見せ方・挙動 / Expected behavior
- ユーザーの操作フローやシステムのフローなど

# 動作環境・ブラウザ / Environment
- 対象としている環境、バグが生じるブラウザや関係するSaaSなど

**Comment by yu23ki14** [comment]
#11

**Comment by osoken** [comment]
#12

**Comment by osoken** [comment]
#20
